name: avocado_utils
description: Collection of utility libraries providing functionalities commonly used in various projects.
version: 0.1.0
repository: https://github.com/Oleksa5/avocado_utils

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
